#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## example of what is a createlinks
##--------------------------------------------------


#mandatory to create db after installation
my $event = 'nethserver-sympa-update';
event_actions ( $event, 'initialize-default-databases' => '00');

event_actions($event, qw(
            nethserver-sympa-create-database 10
            nethserver-sympa-create-sympa-aliases 20
            nethserver-sympa-create-log 30
));
#expand sympas following one event
event_templates($event, qw(
                /etc/httpd/conf.d/default-virtualhost.inc
                /etc/httpd/conf.d/sympa.conf
                /etc/postfix/main.cf
                /etc/sympa/aliases.sympa.postfix
                /etc/sympa/sympa.conf
                /etc/sysconfig/sympa
                /etc/rsyslog.d/sympa.conf
));
#restart services following one event
event_services($event, qw(
               httpd restart
               sympa restart
               wwsympa restart
               sympasoap restart
));
