#!/usr/bin/perl

use strict;
use warnings;
use esmith::DomainsDB;

foreach  (esmith::DomainsDB->open_ro()->get_all_by_prop('type' => 'domain')) {

    my $name = $_->key;
    my $relay = $_->prop('TransportType') || '';
    my $sympa = $_->prop('SympaStatus') || '';
    my $listmaster = $_->prop('SympaListMasters') || '';
    my $lang = $_->prop('SympaLang') || 'en-US';
    next unless ($relay eq 'LocalDelivery');
    next unless ($sympa eq 'enabled');

    mkdir "/etc/sympa/$name";
    mkdir "/var/lib/sympa/list_data/$name";
    mkdir "/var/lib/sympa/list_data/$name/scenari";

    open(my $fh, '>', "/etc/sympa/$name/robot.conf");
    print $fh "wwsympa_url https://$name/sympa\n";
    print $fh "listmaster $listmaster\n" if ($listmaster ne '');
    print $fh "lang $lang\n";
    print $fh "\n";
    close $fh;

    system ("/usr/bin/chown sympa:sympa -R /etc/sympa/$name");
    system ("/usr/bin/chmod 755 /etc/sympa/$name");
    system ("/usr/bin/chmod 644 /etc/sympa/$name/*");
    system ("/usr/bin/chown sympa:sympa -R /var/lib/sympa/list_data/$name");
    system ("/usr/bin/chmod 750 -R /var/lib/sympa/list_data/$name");
}
